services:
  
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  
  kafka:  
    container_name: kafka
    image: quay.io/debezium/kafka:2.7
    ports:
     - 9092:9092
    depends_on:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
     - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  
  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  
  postgres-target:
    container_name: postgres-target
    image: quay.io/debezium/example-postgres:2.7
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  
  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.7
    ports:
     - 8083:8083
    depends_on:
     - kafka
     - mysql
     - postgres-target
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses