connections:
  - name: mysql
    databaseName: inventory
    schemaName: inventory
    dbType: mysql
    url: jdbc:mysql://debezium:dbz@localhost:3306/inventory
    userName: debezium
    password: dbz
    tables:
      - customers
  - name: kinetica
    databaseName: kinetica
    schemaName: inventory
    dbType: kinetica
    url: jdbc:kinetica:URL=http://localhost:9191;CombinePrepareAndExecute=1;
    userName: admin
    password: Admin123!
  
